### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by helio-frota** [cerker/cuckoo-example#1]
Hi @cerker, 

I'm trying to use the example and i get this:

java.lang.ClassCastException: org.cuckoo.ra.cci.CuckooMappedRecord cannot be cast to javax.resource.cci.IndexedRecord 

``` java
IndexedRecord returnTable = (IndexedRecord) output.get("RETURN");
for (Object row : returnTable) {
  MappedRecord record = (MappedRecord) row;
  System.out.println(record.get("MESSAGE"));
}
```

thanks and congrats for this project.

**Comment by cerker** [comment]
Hi @eprogramming ,
when the RETURN parameter in SAP is a table parameter, Cuckoo maps it to an IndexedRecord which itself contains MappedRecords for each row.
However, when the RETURN parameter is a structure parameter in ABAP, it is mapped to a MappedRecord. (Both variants are common.)
Please check which kind of parameter this is in ABAP.
Thanks
Carsten

**Comment by helio-frota** [comment]
Hi @cerker 
Working fine ! 
Thanks !

**Comment by cerker** [comment]
Great it works now. You're welcome...
Closing the ticket...
